 name: continuous integration
 on: [push]

 jobs:
   build:
     strategy:
       matrix:
         python-version: [3.8]

     runs-on: ubuntu-latest

     steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}

       - name: Display Python version
         run: python -c "import sys; print(sys.version)"

       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt

       - name: Lint with flake8
         run: |
           # all Python files should follow PEP8 (except some notebooks, see setup.cfg)
           python -m flake8 --ignore=E501 duckbot.py helper tests

       - name: Setup project
         run: |
           cp ./example/config.example.ini ./config.ini
           cp ./example/zone.example.csv ./zone.csv
           cp ./example/statement.example.csv ./statement.csv

       - name: Test with pytest
         run: python -m pytest tests --cov=./ --cov-report=xml
